name: Deploy Model with Truss

on:
  push:
    branches:
      - main  # Change to your preferred branch
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust as necessary

      - name: Install Truss CLI
        run: pip install --upgrade truss

      # - name: Package your model
      #   run: truss init ./model-name  # Change ./model-name to your model's directory

      - name: Deploy your model
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          truss push --api-key $API_KEY
      - name: Watch for live reload workflow
        run: truss watch