name: Deploy Model with Truss

on:
  push:
    branches:
      - main  # Change to your preferred branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust as necessary

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/basetenlabs/truss.git requests tenacity --upgrade

      - name: Deploy Pushing on Baseten
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: export API_KEY=API_KEY
        run: python bin/test_truss_deploy.py
